name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload Maven package
      uses: actions/upload-artifact@v2
      with:
        name: maven-package
        path: target/*.jar

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build with MSBuild
      run: msbuild HelloWorld.vcxproj /p:Configuration=Debug /p:Platform=Win32